global using CrimeAPI.Data.DbConfig;
global using CrimeAPI.Data.MongoDb.Interfaces;
global using CrimeAPI.Data.MongoDb.Service;
global using AutoMapper;
global using CrimeAPI.Data.DTOs;
global using CrimeAPI.Data.Models;
global using CrimeAPI.Services.Interfaces;
global using CrimeAPI.Services;
global using Microsoft.AspNetCore.Mvc;
