version: '3.4'

services:
  crimeapi:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: CrimeAPI/Dockerfile

  enforcerapi:
    image: ${DOCKER_REGISTRY-}enforcerapi
    build:
      context: .
      dockerfile: Enforcer.API/Dockerfile
  
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongo-db-data:/data/db 

  mongodb-stats:
    image: mongo
    container_name: mongo-stats
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    volumes:
      - mongo-stats-db-data:/data/db 

  mssqldb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: Hospital.Database
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
        - 1433:1433
    volumes:
      - mssql-db-data:/var/opt/mssql 

  statsapi:
    image: ${DOCKER_REGISTRY-}statsapi
    build:
      context: .
      dockerfile: StatsAPI/Dockerfile

volumes:
  mongo-db-data:
  mssql-db-data:
  mongo-stats-db-data:
